### ISSUE TITLE
图形 new-drawio-diagram-icon 太大了

### ISSUE THREAD

**Issue by Zacharia2** [Gk0Wk/TiddlySeq#14]
测试感觉应该为 width="16pt" height="16pt" ，刚刚好。

**Comment by Gk0Wk** [comment]
现在是怎样的？我这里和其他图标一样大

**Comment by Zacharia2** [comment]
![image](https://github.com/Gk0Wk/TiddlySeq/assets/32425955/156fcc10-eaa9-488f-a5d9-64b0b939c1af)

就是这么大。

**Comment by oflg** [comment]
我修了下，一会PR。

之前：
![image](https://github.com/Gk0Wk/TiddlySeq/assets/42492105/fb32a0fb-2c63-4a30-b924-64cc14277021)
之后：
![image](https://github.com/Gk0Wk/TiddlySeq/assets/42492105/45b1721a-ba9e-4a2b-88d6-66ab4bd2764d)
